:lock: fix: Fix security vulnerability allowing people to restart host from inside container, use up all ram or cpu and many others
Signed-off-by: kokodev <koko@kokodev.cc>

diff --git a/templates/install_script.sh.j2 b/templates/install_script.sh.j2
--- a/templates/install_script.sh.j2
+++ b/templates/install_script.sh.j2
@@ -27,8 +27,8 @@ python3 -m venv /etc/venv
 if [ ! -f "$BASH_RC" ]; then
     echo "Creating $BASH_RC and adding 'echo \"hi\"'"
     echo '. /etc/venv/bin/activate' > "$BASH_RC"
-    echo 'nohup python3 /etc/agent/agent.py > /dev/tty 2>&1 &' >> "$BASH_RC"
-    echo 'echo "hi"' >> "$BASH_RC"
+    echo 'echo "Your current internal ip address is "' >> "$BASH_RC"
+    echo 'hostname -i' >> "$BASH_RC"
 else
     echo "$BASH_RC already exists."
 fi
@@ -41,6 +41,26 @@ if [ ! -f "$BASH_PROFILE" ]; then
 else
     echo "$BASH_PROFILE already exists."
 fi
+
+CRON_JOB="@reboot /etc/venv/bin/python3 /etc/agent/agent.py >> /var/log/agent.log 2>&1"
+CRON_FILE="mycron"
+
+crontab -l > $CRON_FILE 2>/dev/null
+
+# Check if the cron job already exists
+if ! grep -Fxq "$CRON_JOB" $CRON_FILE
+then
+    # Add the new cron job
+    echo "$CRON_JOB" >> $CRON_FILE
+    # Install the new cron file
+    crontab $CRON_FILE
+    echo "Cron job added successfully."
+else
+    echo "Cron job already exists."
+fi
+
+# Clean up temporary file
+rm $CRON_FILE
 
 # Verify that the virtual environment is activated and pip is available
 pip --version
